[package]
name = "clustervms"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
figment = { version = "0.10.8", features = ["toml"] }
serde = { version = "1.0.145", features = ["derive"] }
toml = "0.5.9"
url = { version = "2.3.1", features = ["serde"] }
